name: PlantUML Native Image


on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest
    
    container:
      image: "ghcr.io/graalvm/graalvm-ce:22.2.0"

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: bash ./install.sh

      - name: Download
        run: bash ./download.sh

      - name: Build
        run: bash ./build.sh

      - name: Test
        run: bash ./test.sh
